### ISSUE TITLE
fetch service from consul very slow using consuldotnet

### ISSUE THREAD

**Issue by rider11-dev** [ThreeMammals/Ocelot#349]
Sorry to bother you again.
When we request an api through gateway(using ReRoutes configuration in Consul),it appears very slow,almost 2 seconds.I'm using all local websites,including Consul from local.

I debugged the Ocelot srouce code ,and found that it will take more than 1 sec in ConsulServiceDiscoveryProvider.Get ,to be exact ,it's await _consul.Health.Service(_config.KeyOfServiceInConsul, string.Empty, true)!
Below is my log data(notice the ConsulServiceDiscoveryProvider logger part):
[ocelot-consul.log](https://github.com/ThreeMammals/Ocelot/files/1986158/ocelot-consul.log)

I tried 3 times,more than 1 sec in average.
______________________________________________________________________________________________
And I found the ConsulClientFactory,and changed it as below(make IConsulClient a Cache):
![image](https://user-images.githubusercontent.com/16696623/39792291-7f674c68-5372-11e8-8a30-57ad702a1b51.png)
It flys,as the follow log data shows:
[ocelot-consul-new.log](https://github.com/ThreeMammals/Ocelot/files/1986190/ocelot-consul-new.log)
______________________________________________________________________________________________
So could you think about this case?
Since above modify in  ConsulClientFactory is just a simple try,you master must have your own consideration.
And it still cost more than 100 ms,I think we can think about service cache in Ocelot.
Thanks very much!

**Comment by TomPallister** [comment]
@zpf1989 I have had a quick look now, the IConsulClient is cached later on as part of LoadBalancerHouse so it should only be created once per ReRoute. Unless I am missing something I probably am so will keep looking as it is clear from log you are spending more time in Consul code.

Were you using Console logging for either of these tests?

**Comment by zpf1989** [comment]
Yeah,I have logging in Console either,and Consul is also has its Console terminal.
With logging in Console  disabled,It appears faster,but the 1 sec still exists.
I debug the ConsulClientFactory using F5,found that every request will create a new ConsulClient,even for the same ReRoute.
Hope to help.

**Comment by TomPallister** [comment]
@zpf1989 OK thanks for the information, please could you share you json configuration so I can debug this further. It should not be creating a new client for each request.

**Comment by zpf1989** [comment]
Sorry to provide the configuration in consul so late,Here is it:
[config_in_consul.txt](https://github.com/ThreeMammals/Ocelot/files/1989883/config_in_consul.txt)
And below is in the ocelot.json file under my gateway website,
{
  "GlobalConfiguration": {
    "RequestIdKey": "RequestId",
    "ServiceDiscoveryProvider": {
      "Provider": "Consul",
      "Host": "localhost",
      "Port": 8500
    }
  }
}
If I missed something,tell me please.
Thank you!

**Comment by TomPallister** [comment]
@zpf1989 Thanks for sharing I will take a look. It might be something to do with the fact your are also storing the configuration in Consul. I do not have a test for this. I will check again asap.

**Comment by TomPallister** [comment]
@zpf1989 I am sorry but I'm not sure if I will have time to debug this before 14/05/2018. If you have time I suggest trying your configuration in the ocelot configuration.json and see if you get the same problem. If you don't we know its an issue with storing configuration in Consul.

**Comment by zpf1989** [comment]
I've tried your way,and I got the same problem.
I moved the config from Consul to my ocelot.json file,and removed the AddStoreOcelotConfigurationInConsul.
It's the same problem,as below:
![image](https://user-images.githubusercontent.com/16696623/39952362-57d4bde6-55c7-11e8-8c51-6cdd138c5e42.png)

And I think the problem should not be the position of the configuration.
It's the process that finding service from consul acts slow.
Waiting for your news ,thank you.

**Comment by TomPallister** [comment]
@zpf1989 ok cool, I will take a look ASAP. I am away from my computer at the moment :)

**Comment by TomPallister** [comment]
@zpf1989 This is a bug. I have an if statement to check if we need to rebuild the cached load balancer / service discovery client and it does not account for the user not choosing a load balancer. Ocelot defaults to no load balancer so we need to make the check account for that. I will change this tickets status and will fix the bug asap.

However you can fix this issue by choosing a load balancer in your configuration. If you have a look at the docs [here](http://ocelot.readthedocs.io/en/latest/features/loadbalancer.html#) it should make sense how to choose one.

**Comment by zpf1989** [comment]
Well,as to load balancer,there is a plan to use nginx between the gateway and the api.
Nginx register itself as a service in consul too,and so gateway can find it and  follow requests with servicename APIA to  special nginx server with some custom handling.
But, as you see,it's complex.
So what's your advice about which one would we use,the nginx,or the load balancer inside ocelot?
And what's the difference between the two?
No offense ,just for discuss. :)
Tank you!

**Comment by TomPallister** [comment]
@zpf1989 Ocelot always uses a load balancer abstraction internally. If you don’t set anything it uses NoLoadBalancer. The bug is related to this. If you put NoLoadBalancer in your config your performance issue should be resolved!

Use nginx with Ocelot NoLoadBalancer. Nginx is a much more battle tested piece of software :)

Don’t worry I’m not offended!

**Comment by TomPallister** [comment]
@zpf1989 I have released a fix for this issue in Ocelot version 7.0.2 please can you give it a try and see if the performance is still poor? Let me know if it doesn't improve. I believe you are using the same setup as Tencent apart from this bug so the performance should be good!

**Comment by TomPallister** [comment]
@zpf1989 there was a problem with the release, please wait for further updates

**Comment by zpf1989** [comment]
It works fine and the 1 sec disappear.
But It still cost about 100 ms in gateway ,I have no idea whether it's the same in your test.
It may relate to my local Consul server,consuldotnet,my gateway site,or something else.
I'll keep on it.
Thank you very much!

**Comment by zpf1989** [comment]
Man,it seems to a new bug,see the case below:
I use the no NoLoadBalancer.
First,I start up the gateway only,when request an api,it fails because of no service found in consul.It's OK.
Than, I start the api and request again after it's green in consul,it still fails .
It's the NoLoadBalancer that fetching services from consul for only once(and the NoLoadBalancer is cached),like below:
![image](https://user-images.githubusercontent.com/16696623/40094456-ae36f55c-58f9-11e8-8030-4b8b320fab37.png)
**Should it be the same as RoundRobin to pass a getting services Func to the constructed function?**
![image](https://user-images.githubusercontent.com/16696623/40094557-4852457e-58fa-11e8-8d89-bf2d7b581d4e.png)

**Comment by TomPallister** [comment]
@zpf1989 awesome!! Thank you for your patience! I really appreciate the help.
